<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $priority
 * @property string $title
 * @property clob $summary
 * @property clob $content
 * @property boolean $is_active
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method integer getPriority()  Returns the current record's "priority" value
 * @method string  getTitle()     Returns the current record's "title" value
 * @method clob    getSummary()   Returns the current record's "summary" value
 * @method clob    getContent()   Returns the current record's "content" value
 * @method boolean getIsActive()  Returns the current record's "is_active" value
 * @method News    setId()        Sets the current record's "id" value
 * @method News    setPriority()  Sets the current record's "priority" value
 * @method News    setTitle()     Sets the current record's "title" value
 * @method News    setSummary()   Sets the current record's "summary" value
 * @method News    setContent()   Sets the current record's "content" value
 * @method News    setIsActive()  Sets the current record's "is_active" value
 * 
 * @package    shakmyth
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('priority', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('summary', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'content',
             ),
             ));
        $this->actAs($searchable0);
    }
}