<?php

/**
 * BaseContributorMyth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $profile_id
 * @property integer $myth_id
 * @property Profile $Profile
 * @property Myth $Myth
 * 
 * @method integer         getId()         Returns the current record's "id" value
 * @method integer         getProfileId()  Returns the current record's "profile_id" value
 * @method integer         getMythId()     Returns the current record's "myth_id" value
 * @method Profile         getProfile()    Returns the current record's "Profile" value
 * @method Myth            getMyth()       Returns the current record's "Myth" value
 * @method ContributorMyth setId()         Sets the current record's "id" value
 * @method ContributorMyth setProfileId()  Sets the current record's "profile_id" value
 * @method ContributorMyth setMythId()     Sets the current record's "myth_id" value
 * @method ContributorMyth setProfile()    Sets the current record's "Profile" value
 * @method ContributorMyth setMyth()       Sets the current record's "Myth" value
 * 
 * @package    shakmyth
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseContributorMyth extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contributor_myth');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('profile_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('myth_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Myth', array(
             'local' => 'myth_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}