<?php

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $heading
 * @property integer $priority
 * @property enum $special_page
 * @property string $title
 * @property clob $content
 * @property boolean $is_active
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method enum    getHeading()      Returns the current record's "heading" value
 * @method integer getPriority()     Returns the current record's "priority" value
 * @method enum    getSpecialPage()  Returns the current record's "special_page" value
 * @method string  getTitle()        Returns the current record's "title" value
 * @method clob    getContent()      Returns the current record's "content" value
 * @method boolean getIsActive()     Returns the current record's "is_active" value
 * @method Page    setId()           Sets the current record's "id" value
 * @method Page    setHeading()      Sets the current record's "heading" value
 * @method Page    setPriority()     Sets the current record's "priority" value
 * @method Page    setSpecialPage()  Sets the current record's "special_page" value
 * @method Page    setTitle()        Sets the current record's "title" value
 * @method Page    setContent()      Sets the current record's "content" value
 * @method Page    setIsActive()     Sets the current record's "is_active" value
 * 
 * @package    shakmyth
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('heading', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '',
             ),
             ));
        $this->hasColumn('priority', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('special_page', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '',
             ),
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'heading',
              1 => 'content',
             ),
             ));
        $this->actAs($searchable0);
    }
}