<?php

/**
 * BaseMyth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property boolean $is_active
 * @property Doctrine_Collection $Profiles
 * @property Doctrine_Collection $Myths
 * @property Doctrine_Collection $GroupUsers
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method boolean             getIsActive()   Returns the current record's "is_active" value
 * @method Doctrine_Collection getProfiles()   Returns the current record's "Profiles" collection
 * @method Doctrine_Collection getMyths()      Returns the current record's "Myths" collection
 * @method Doctrine_Collection getGroupUsers() Returns the current record's "GroupUsers" collection
 * @method Myth                setId()         Sets the current record's "id" value
 * @method Myth                setName()       Sets the current record's "name" value
 * @method Myth                setIsActive()   Sets the current record's "is_active" value
 * @method Myth                setProfiles()   Sets the current record's "Profiles" collection
 * @method Myth                setMyths()      Sets the current record's "Myths" collection
 * @method Myth                setGroupUsers() Sets the current record's "GroupUsers" collection
 * 
 * @package    shakmyth
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseMyth extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('myth');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Profile as Profiles', array(
             'refClass' => 'ContributorMyth',
             'local' => 'myth_id',
             'foreign' => 'profile_id'));

        $this->hasMany('MythPage as Myths', array(
             'local' => 'id',
             'foreign' => 'myth_id'));

        $this->hasMany('ContributorMyth as GroupUsers', array(
             'local' => 'id',
             'foreign' => 'myth_id'));
    }
}