all:
  sfGuardAuthModuleLib:
    dir: <?php echo sfConfig::get('sf_plugins_dir').'/sfDoctrineGuardPlugin/modules/sfGuardAuth/lib' ?>
  
  sfGuardUserModuleLib:
    dir: <?php echo sfConfig::get('sf_plugins_dir').'/sfDoctrineGuardPlugin/modules/sfGuardUser/lib' ?>

  mail-from-title: The Shakmyth website administrators
  mail-subject:    Notification Mail
  
  sf_zend_mail:    
    charset: utf-8
    encoding: quoted-printable
    transport:
      # sample with Sendmail
      #class: Zend_Mail_Transport_Sendmail      # Zend_Mail_Transport_Sendmail | Zend_Mail_Transport_Smtp
      #parameters: "-ffrom@yourdomain.com"

      # sample with Smtp
      class: Zend_Mail_Transport_Smtp          # Zend_Mail_Transport_Sendmail | Zend_Mail_Transport_Smtp
      parameters: 
        - 91.121.24.110                            # URL or IP of the smtp server
        #- { auth: Plain|Crammd5|Login, username: yourusername, password: yourpassword }  #if required, else don't set

    decorator:                                 # define the layout use in the mail
      enabled: off                             # on | off : set true if all your mail share the same layout
      directory: "%SF_APP_TEMPLATE_DIR%"       # where the layout is located, ie %SF_APP_TEMPLATE_DIR%
      template: email                          # name of the layout, automatically translate to name.FORMAT.php
    view:                                      # define the view class used to render the template
      class: sfZendMailView

  sf_media_browser:
    assets_list:                           
      js:  [/js/jquery.js, /js/jquery.dragndrop.js, /sfMediaBrowserPlugin/js/list.jquery.js]
      css: [/sfMediaBrowserPlugin/css/list.css]
      
dev:
  mail-from:  'stephane.langlois@particul.es'
  
prod: 
  mail-from:  'contact@shakmyth.org'