<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GlobalDoctrineModel extends Doctrine_Table
{
  static public function searching($obj, $query)
  {
    $className = preg_replace("/Table/", "", get_class($obj));
   
    $q = Doctrine_Query::create()
        ->from($className.' i');

    $q = $obj->search($query, $q);

    return $q->execute();
  }
}