<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MythTable extends Doctrine_Table
{
  public function getMythsWithFirstLetter($firstLetter = "a", $is_active = FALSE)
  {
    $q = $this->createQuery('m')
      ->where('m.name LIKE ?', $firstLetter."%");
    $q = DocTools::addIsActive($q, $is_active);
      
    return  $q->execute();
  }
  
  public function getLettersAndMythCount($is_active = FALSE) 
  {
    $i = 0;
    $letters = array();
    while ($i++ < 26) 
    {
      $letters[chr(64+$i)] = self::getMythsWithFirstLetter(chr(64+$i), $is_active)->count();  
    }

    return $letters;
  }
  
  public function createWidgetChoicesWithProfileId($profile_id, $is_active = null)
  {
    $myths = array('' => '');
    $myths_by_profile = Doctrine::getTable('Profile')->getMythsById($profile_id, $is_active);
    
    foreach ($myths_by_profile as $myth) 
    {
      $myths[$myth->getId()] = $myth->getName();
    }
     
    return $myths;
  }
}