<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Myth extends BaseMyth
{ 
  public function save(Doctrine_Connection $conn = null)
  {  
    parent::save($conn);
    
    return self::renewIsActive();
  }
  
  public function renewIsActive()
  {
    // active this myth when a myth page is actived
    $is_active = (is_null(Doctrine::getTable('MythPage')->countMythPages($this->getId(), $is_active = true))) ?  false : true;

    if ($this->getIsActive() === $is_active)
    {
      return null;
    }
    
    $this->setIsActive($is_active);
         
    return $this->save();
  }
}