<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MythPage extends BaseMythPage
{    
  public function setup()
  {      
    parent::setup();    
    $this
      ->getTable()
      ->getTemplate('Doctrine_Template_Searchable')
      ->getPlugin()
      ->setOption('analyzer', new DocAnalyzer());
  }
  
  public function save(Doctrine_Connection $conn = null)
  { 
	parent::save($conn);
    
    return $this->getMyth()->renewIsActive();
  }
  
  public function delete(Doctrine_Connection $conn = null)
  { 
    parent::delete($conn);
        
    return $this->getMyth()->renewIsActive();
  }
  
  public function getMythName()
  {
    return $this->getMyth()->getName();
  }
}