<?php

/**
 * news
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    shakmyth
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class news extends Basenews
{
  public function getSummary()
  {
    $summary = $this->_get('summary');
    return $summary ? $summary : Tools::resume($this->content);
  }
}
