<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Page extends BasePage
{
  public function setup()
  {  
    parent::setup();    
    $this
      ->getTable()
      ->getTemplate('Doctrine_Template_Searchable')
      ->getPlugin()
      ->setOption('analyzer', new DocAnalyzer());
  }
}