<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileTable extends Doctrine_Table
{ 
  public function getBySearch($query)
  {
    
    return GlobalDoctrineModel::searching($this, $query);
  }
    
  public function getMythsById($profile_id, $is_active = null) 
  { 
    $q = $this->createQuery('p')
      ->leftJoin('p.Myths m')
      ->where('p.id ='.$profile_id);

    ($is_active === true || $is_active === false) ? $q->addWhere('m.is_active = ?', $is_active) : null;
    $myths = ($q->execute()->getFirst() != false) ? $q->execute()->getFirst()->getMyths() : null;
    
    return $myths;
  }
  
  public function getProfilesByMythId($myth_id, $is_active = null)
  {
    $q = $this->createQuery('p')
      ->leftJoin('p.Myths m')
      ->leftJoin('p.User u')
      ->where('m.id ='.$myth_id);

    ($is_active === true || $is_active === false) ? $q->addWhere('u.is_active = ?', $is_active) : null;

    return $q->execute();
  }

  public function getActiveContributors()
  {
	  $q = $this->createQuery('p')
	    ->leftJoin('p.User u')
      ->leftJoin('u.groups g')
      ->where('u.is_active = true')
			->orderBy('p.last_name')
			->andWhere('g.name != ?', "admin");

    return $q->execute();
  }
}
