<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Profile extends BaseProfile
{  
  public function __toString()
  {
    return ucfirst($this->getFirstName()).' '.ucfirst($this->getLastName());
  }

  public function setup()
  {            
    parent::setup();    
    $this
      ->getTable()
      ->getTemplate('Doctrine_Template_Searchable')
      ->getPlugin()
      ->setOption('analyzer', new DocAnalyzer());
  }
  
  public function getPhoto()
  {  
    if (!is_file(sfConfig::get('sf_web_dir').sfConfig::get('app_identities_dir').'/'.$this->_get('photo')))
    {
      $this->photo = sfConfig::get('app_identities_default'); 
    }
    
    return $this->_get('photo');
  }
  
  public function save(Doctrine_Connection $conn = null)
  {
    return parent::save($conn);
    
    $login = $this->getUser()->getUserName();
    $password = $this->getUser()->getPassword();
    $password = "xxxxxxxx";
    
    if ($this->isNew())
    {
      // send an email to the affiliate
      ProjectConfiguration::registerZend();
      $mail = new Zend_Mail();
      $mail->setBodyText(<<<EOF
Dear Contributor,

This is to let you know that an account has been created for you on the Shakmyth website. You may access your account by clicking on the following link http://shakmyth.org/admin. 

Your login is $login and your password $password.

Welcome aboard!

Best wishes,

The Shakmyth website administrators
EOF
);
      $mail->setFrom(sfConfig::get('app_mail-from'), sfConfig::get('app_mail-from-title'));
      $mail->addTo($this->getUser()->getUserName());
      $mail->setSubject(sfConfig::get('app_mail-subject'));
      $mail->send();
    }
 
    return parent::save($conn);
  }
}