<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
  public function getActiveContributors()
  {
    $q = Doctrine::getTable('sfGuardUser')
      ->createQuery('m')
      ->leftJoin('m.groups g')
      ->where('m.is_active = true');  

/*
	TODO ->andWhere('g.name = ?', "contributor");
*/
    return $q->execute();
  }
}