all:
  bad-words:
    uk:
      - lorem
      - about
      - above
      - according
      - across
      - actually
      - adj
      - after
      - afterwards
      - again
      - against
      - all
      - almost
      - alone
      - along
      - already
      - also
      - although
      - always
      - among
      - amongst
      - amp
      - an
      - and
      - another
      - any
      - anyhow
      - anyone
      - anything
      - anywhere
      - are
      - area
      - aren
      - arent
      - around
      - as
      - at
      - available
      - back
      - be
      - became
      - because
      - become
      - becomes
      - becoming
      - been
      - before
      - beforehand
      - begin
      - beginning
      - behind
      - being
      - below
      - beside
      - besides
      - best
      - better
      - between
      - beyond
      - big
      - billion
      - bit
      - both
      - but
      - by
      - came
      - can
      - cannot
      - cant
      - capable
      - caption
      - co
      - control
      - could
      - couldnt
      - course
      - dan
      - day
      - decided
      - did
      - didn
      - didnt
      - different
      - div
      - do
      - does
      - doesn
      - doesnt
      - don
      - dont
      - down
      - drive
      - during
      - each
      - easily
      - easy
      - edition
      - eg
      - eight
      - eighty
      - either
      - else
      - elsewhere
      - end
      - ending
      - enough
      - etc
      - even
      - ever
      - every
      - everyone
      - everything
      - everywhere
      - example
      - except
      - few
      - fifty
      - find
      - first
      - five
      - for
      - former
      - formerly
      - forty
      - found
      - four
      - from
      - further
      - get
      - go
      - going
      - good
      - got
      - gt
      - had
      - hard
      - has
      - hasnt
      - have
      - havent
      - he
      - hence
      - her
      - here
      - hereafter
      - hereby
      - herein
      - heres
      - hereupon
      - hers
      - herself
      - hes
      - him
      - himself
      - his
      - how
      - however
      - hundred
      - ie
      - if
      - in
      - inc
      - indeed
      - instead
      - into
      - is
      - isn
      - isnt
      - it
      - its
      - itself
      - just
      - know
      - last
      - later
      - latter
      - latterly
      - least
      - left
      - less
      - let
      - li
      - like
      - likely
      - little
      - ll
      - long
      - look
      - lot
      - lt
      - ltd
      - made
      - make
      - makes
      - many
      - may
      - maybe
      - mb
      - me
      - meantime
      - meanwhile
      - menu
      - might
      - million
      - miss
      - mm
      - more
      - moreover
      - most
      - mostly
      - mr
      - mrs
      - much
      - must
      - my
      - myself
      - name
      - namely
      - nbsp
      - need
      - neither
      - never
      - nevertheless
      - new
      - next
      - nine
      - ninety
      - no
      - nobody
      - none
      - nonetheless
      - noone
      - nor
      - not
      - nothing
      - now
      - nowhere
      - number
      - of
      - off
      - often
      - old
      - on
      - once
      - one
      - only
      - onto
      - or
      - original
      - other
      - others
      - otherwise
      - our
      - ours
      - ourselves
      - out
      - over
      - overall
      - own
      - page
      - part
      - per
      - perhaps
      - place
      - point
      - pretty
      - probably
      - problem
      - put
      - quite
      - quot
      - rather
      - re
      - really
      - recent
      - recently
      - results
      - right
      - same
      - saw
      - see
      - seem
      - seemed
      - seeming
      - seems
      - set
      - seven
      - seventy
      - several
      - she
      - sherree
      - shes
      - should
      - shouldnt
      - since
      - six
      - sixty
      - size
      - small
      - some
      - somehow
      - someone
      - something
      - sometime
      - sometimes
      - somewhere
      - special
      - still
      - stop
      - stuff
      - such
      - sure
      - system
      - take
      - taking
      - ten
      - than
      - that
      - the
      - their
      - them
      - themselves
      - then
      - thence
      - there
      - thereafter
      - thereby
      - therefore
      - therein
      - thereupon
      - these
      - they
      - thing
      - things
      - think
      - thirty
      - this
      - those
      - though
      - thousand
      - three
      - through
      - throughout
      - thru
      - thus
      - time
      - tips
      - to
      - today
      - together
      - too
      - took
      - toward
      - towards
      - trillion
      - twenty
      - two
      - under
      - unless
      - unlike
      - unlikely
      - until
      - up
      - update
      - updated
      - updates
      - upon
      - us
      - use
      - used
      - using
      - ve
      - very
      - via
      - want
      - wanted
      - wants
      - was
      - wasnt
      - way
      - ways
      - we
      - wed
      - well
      - went
      - were
      - werent
      - what
      - whatever
      - whats
      - when
      - whence
      - whenever
      - where
      - whereafter
      - whereas
      - whereby
      - wherein
      - wheres
      - whereupon
      - wherever
      - whether
      - which
      - while
      - white
      - whither
      - who
      - whoever
      - whole
      - whom
      - whomever
      - whose
      - why
      - will
      - with
      - within
      - without
      - wont
      - work
      - worked
      - working
      - works
      - would
      - wouldnt
      - yes
      - yet
      - you
      - youd
      - youll
      - your
      - youre
      - yours
      - yourself
      - yourselves
      - youve