items:
  item1: Home
  item2: Dictionary
  item3: EEMTS
  item4: SEMM
  item5: Bibliography
  item6: 'Events & Links'
  item7: Contributors
  item8: Contact us
  item9: Search entire website
  item10: Contributors
  item11: Restricted access
