generator:
  class: sfDoctrineGenerator
  param:
    model_class:           News
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [=title, priority, is_active]
        batch_actions:
          _delete:    ~
          actived:    ~
          inactived:  ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
