<?php
class sfDoctrineSchemaRelation extends sfDoctrineSchemaElement
{
  protected
    $_template = array(
      'local'       => '',
      'foreign'     => '',
      'class'       => '',
      'alias'       => '',
      'foreignAlias'=> '',
      'type'        => 0,
      'foreignType' => 1
    );

  protected function _clean(array &$data)
  {
    unset($data['key'], $data['autogenerated']);
  }
}